### ISSUE TITLE
可以教我一下怎么用的吗？

### ISSUE THREAD

**Issue by car520120** [tkzcfc/vpn_uv#1]
我想用ddns 免费域名 绑定端口  转发 smb 服务共享网盘的 
主要是我不知道你这个怎么用的
能不能把cmake  换成 xmake 吗？
谢谢的了
主要是 webdav 协议会导致大文件不好处理，所以想到用你这个方案的，谢谢的了

**Comment by tkzcfc** [comment]
这还是个socks5代理隧道 实现不了你说的功能  你用这个吧  https://github.com/ehang-io/nps

**Comment by car520120** [comment]
我主要是以学习为主的想了解一下 libuv 这个库的基本使用的，你能搭个例子给我吗？我看了这个工程是有客户端和服务端的，我看了你的 test 只有协议部分的，但是不知道 服务端是怎么和客户端连在一起调试的

**Comment by tkzcfc** [comment]
test的东西不用管那只是测试消息解码的  你只需要运行 client和sever然后在浏览器里面装个代理插件  选择socks5 端口设置为客户端监听端口   然后再使用浏览器访问的时候所以流量都会走client -> sever-> 网络  这条隧道

**Comment by tkzcfc** [comment]
如果把server放在境外的服务器上  就实现了翻墙的效果
