### ISSUE TITLE
Problem to compile

### ISSUE THREAD

**Issue by amunhoz** [tkzcfc/vpn_uv#2]
Hi there! I'm trying to compile to test your code, but i get errors in include files: 

/home/user/git/temp/proxy/vpn_uv-1.1/ThirdParty/libuv/src/unix/aix-common.c:45:10: fatal error: sys/protosw.h: No such file or directory
/home/user/git/temp/proxy/vpn_uv-1.1/ThirdParty/libuv/src/unix/aix-common.c:46:10: fatal error: procinfo.h: No such file or directory

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal

I'm not very experient in c++, so i dont know how to solve it.

Thanks in advance.

**Comment by tkzcfc** [comment]
Sorry, I don't have a Linux compilation environment. This error should be that the corresponding header file cannot be found when compiling libuv. You need to search Google for the compilation of libuv on Linux

**Comment by amunhoz** [comment]
Thanks, will check.
